<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'firstname' => 'Jorge',
                'lastname' => 'Sosa',
                'email' => 'admin@mail.com',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345678',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => '123 Main St',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Abinadí',
                'lastname' => 'López',
                'email' => 'abinadilopez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345679',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'México',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Alain',
                'lastname' => 'Aguilar',
                'email' => 'alainaguilar@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345680',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Bolivia',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Alejandro',
                'lastname' => 'Hernandez',
                'email' => 'alejandrohernandez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345681',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Guatemala',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Angelo',
                'lastname' => 'Balvin',
                'email' => 'angelobalvin@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345682',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Daniel',
                'lastname' => 'Gomez',
                'email' => 'danielgomez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345683',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'México',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'David',
                'lastname' => 'Vilchis',
                'email' => 'davidvilchis@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345684',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'México',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Dorian',
                'lastname' => 'Merino',
                'email' => 'dorianmerino@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345685',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Colombia',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Edgar',
                'lastname' => 'Gil',
                'email' => 'edgargil@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345686',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Edgar',
                'lastname' => 'Trujillo',
                'email' => 'edgartrujillo@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345687',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Ecuador',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Edwin',
                'lastname' => 'Moreno',
                'email' => 'edwinfuentes@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345688',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Colombia',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Erick',
                'lastname' => 'Bolivia',
                'email' => 'erickbolivia@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345689',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Faraday',
                'lastname' => 'Aldaz',
                'email' => 'faradayaldaz@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345690',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'México',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Gerald',
                'lastname' => 'Saavedra',
                'email' => 'geraldsaavedra@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345691',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Jacques',
                'lastname' => 'Oliver',
                'email' => 'olivierjacques@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345692',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Haití',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Jampier',
                'lastname' => 'Ticona',
                'email' => 'jampierticona@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345693',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Bolivia',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Jhossimar',
                'lastname' => 'Condori',
                'email' => 'jhossimarcondori@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345694',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'José',
                'lastname' => 'Casado',
                'email' => 'josecasado@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345695',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'República Dominicana',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'José',
                'lastname' => 'Méndez',
                'email' => 'josemendez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345696',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Guatemala',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'José',
                'lastname' => 'Morales',
                'email' => 'josemorales@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345697',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Guatemala',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'José',
                'lastname' => 'Ramirez',
                'email' => 'joseramirez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345698',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Bolivia',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Juan',
                'lastname' => 'Martinez',
                'email' => 'juanmartinez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345699',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Venezuela',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Junior',
                'lastname' => 'Ernest',
                'email' => 'ernstlouissaint@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345700',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Haití',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Lorena',
                'lastname' => 'Escribano',
                'email' => 'lorenaescribano@fundaciondevalores.org',
                'gender' => 2,
                'document_type' => 1,
                'document_number' => '12345701',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Marcos',
                'lastname' => 'Chacaltana',
                'email' => 'marcoschacaltana@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345702',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Marcos',
                'lastname' => 'Elvira',
                'email' => 'marcoselvira@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345703',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Guatemala',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Miguel',
                'lastname' => 'Moreno',
                'email' => 'miguelmoreno@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345704',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Ecuador',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Miguel',
                'lastname' => 'Perez',
                'email' => 'miguelperez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345705',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Mónica',
                'lastname' => 'Gonzáles',
                'email' => 'monicagonzales@fundaciondevalores.org',
                'gender' => 2,
                'document_type' => 1,
                'document_number' => '12345706',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Nilson',
                'lastname' => 'Jimenez',
                'email' => 'nilsonjimenez@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345707',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'República Dominicana',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Rafael',
                'lastname' => 'Piedrahita',
                'email' => 'josepiedrahita@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345708',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Venezuela',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Roque',
                'lastname' => 'Zaldaña',
                'email' => 'roquezaldana@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345709',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'El Salvador',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Samuel',
                'lastname' => 'Vera',
                'email' => 'axelvera@fundaciondevalores.org',
                'gender' => 1,
                'document_type' => 1,
                'document_number' => '12345710',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'México',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstname' => 'Virginia',
                'lastname' => 'Sanchez',
                'email' => 'dorasanchez@fundaciondevalores.org',
                'gender' => 2,
                'document_type' => 1,
                'document_number' => '12345711',
                'birth_date' => '1990-01-01',
                'marital_status' => 1,
                'address' => 'Perú',
                'contact_phone_1' => '1234567890',
                'contact_phone_2' => '0987654321',
                'password' => bcrypt('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // assign the admin role to the user
        $adminUser = User::where('email', 'admin@mail.com')->first();
        $adminUser->assignRole('Administrador');

        // assign the Responsable role to all other users
        $responsableUsers = User::whereNotIn('email', ['admin@mail.com'])->get();
        foreach ($responsableUsers as $user) {
            $user->assignRole('Responsable');
        }
    }
}
